# Generated by Django 5.1 on 2024-08-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='line_total',
        ),
    ]
