# Generated by Django 5.1 on 2024-09-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_price',
        ),
    ]
