# Generated by Django 5.1 on 2024-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sum_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
