# Generated by Django 5.1 on 2024-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoiceitem_sum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
