# Generated by Django 5.1 on 2024-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoiceitem_net_price_alter_invoice_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
